# Generated by Django 4.2.28 on 2026-02-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_slot', models.CharField(choices=[('10:00', '10:00 AM - 10:20 AM'), ('12:00', '12:00 PM - 12:30 PM'), ('13:00', '1:00 PM - 1:30 PM'), ('15:00', '3:00 PM - 3:20 PM')], max_length=5)),
                ('forecast_date', models.DateField()),
                ('day_of_week', models.IntegerField()),
                ('predicted_quantity', models.IntegerField(default=0)),
                ('actual_quantity', models.IntegerField(default=0)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_slot', models.CharField(choices=[('10:00', '10:00 AM - 10:20 AM'), ('12:00', '12:00 PM - 12:30 PM'), ('13:00', '1:00 PM - 1:30 PM'), ('15:00', '3:00 PM - 3:20 PM')], max_length=5)),
                ('pickup_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('ready', 'Ready for Pickup'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('special_instructions', models.TextField(blank=True)),
                ('token_number', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estimated_ready_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('break_slot', models.CharField(choices=[('10:00', '10:00 AM - 10:20 AM'), ('12:00', '12:00 PM - 12:30 PM'), ('13:00', '1:00 PM - 1:30 PM'), ('15:00', '3:00 PM - 3:20 PM')], max_length=5)),
                ('total_orders', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avg_prep_time', models.FloatField(default=0)),
                ('peak_hour', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_at_order', models.DecimalField(decimal_places=2, max_digits=8)),
                ('customization', models.TextField(blank=True)),
            ],
        ),
    ]
