# Generated by Django 4.2.28 on 2026-02-21 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stalls', '0001_initial'),
        ('orders', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demandforecast',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stalls.menuitem'),
        ),
        migrations.AddField(
            model_name='demandforecast',
            name='stall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='stalls.foodstall'),
        ),
        migrations.AlterUniqueTogether(
            name='orderanalytics',
            unique_together={('stall', 'date', 'break_slot')},
        ),
        migrations.AlterUniqueTogether(
            name='demandforecast',
            unique_together={('stall', 'menu_item', 'break_slot', 'forecast_date')},
        ),
    ]
